# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "Marks" ("ID" SERIAL NOT NULL PRIMARY KEY,"NAME" VARCHAR(254) DEFAULT '' NOT NULL,"READING" DOUBLE PRECISION DEFAULT 0.0 NOT NULL,"LISTENING" DOUBLE PRECISION DEFAULT 0.0 NOT NULL,"WRITING" DOUBLE PRECISION DEFAULT 0.0 NOT NULL,"SPEAKING" DOUBLE PRECISION DEFAULT 0.0 NOT NULL,"TOTAL" DOUBLE PRECISION DEFAULT 0.0 NOT NULL);
create table "Rtext" ("ID" SERIAL NOT NULL PRIMARY KEY,"Rtext" VARCHAR(254) DEFAULT '' NOT NULL,"RTitle" VARCHAR(254) DEFAULT '' NOT NULL);

# --- !Downs

drop table "Rtext";
drop table "Marks";

